In [20]:
import numpy as np
import pandas as pd

In [21]:
r_pancreas = pd.read_csv("ligands_receptors/pancreas_ht224p1/receiver_mean.csv")
s_pancreas = pd.read_csv("ligands_receptors/pancreas_ht224p1/sender_mean.csv")

r_sein = pd.read_csv("ligands_receptors/sein_ht425b1/receiver_mean.csv")
s_sein = pd.read_csv("ligands_receptors/sein_ht425b1/sender_mean.csv")

In [27]:
r_pancreas.drop(7)

,cell_type,r-PLG-F2R,r-PLG-F2RL3,r-PLG-PARD3,r-PLG-F2RL1,r-PLG-F2RL2,r-UCN2-CRHR1,r-UCN2-CRHR2,r-IL9-IL9R_IL2RG,r-FSHB-FSHR,...,r-INSL3-RXFP1,r-INSL3-RXFP3,r-INSL3-RXFP2,r-INSL3-RXFP4,r-APLN-APLNR,r-IAPP-CALCR,r-IAPP-CALCRL,r-INHBA-ACVR1B_ACVR2B,r-INHBA-ACVR1B_ACVR2A,r-total-total
0,ADM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,12.372126
1,B-cells,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.339451
2,Ductal-like1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.509176
3,Ductal-like2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,20.364005
4,Endothelial,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,20.638559
5,Fibroblasts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000377,0.0,0.0,0.0,0.001602,0.0,0.002803,0.002427,0.026371,21.002141
6,Islets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.045629,0.000000,16.656341
8,Macrophages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.002563,0.0,0.000671,0.003941,0.012111,24.217980
9,Mast,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.509176
10,Other_doublets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,11.288639
11,Plasma,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.005292,0.0,0.012797,0.000000,0.010571,14.735264
12,T-cells,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.001415,0.0,0.007817,0.009416,0.005669,23.735394
13,Tumor,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000443,0.0,0.0,0.0,0.001349,0.0,0.002293,0.002412,0.025519,20.044272

In [24]:
s_pancreas.drop(7)

,cell_type,s-PLG-F2R,s-PLG-F2RL3,s-PLG-PARD3,s-PLG-F2RL1,s-PLG-F2RL2,s-UCN2-CRHR1,s-UCN2-CRHR2,s-IL9-IL9R_IL2RG,s-FSHB-FSHR,...,s-INSL3-RXFP1,s-INSL3-RXFP3,s-INSL3-RXFP2,s-INSL3-RXFP4,s-APLN-APLNR,s-IAPP-CALCR,s-IAPP-CALCRL,s-INHBA-ACVR1B_ACVR2B,s-INHBA-ACVR1B_ACVR2A,s-total-total
0,ADM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000200,0.000000,13.090491
1,B-cells,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,3.327665
2,Ductal-like1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.028021
3,Ductal-like2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000070,22.152625
4,Endothelial,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000040,18.901334
5,Fibroblasts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000499,0.0,0.0,0.0,0.001627,0.0,0.003568,0.002270,0.027645,21.095170
6,Islets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.084481,0.001055,17.449338
8,Macrophages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.001085,0.0,0.000671,0.001861,0.009820,24.238259
9,Mast,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.028021
10,Other_doublets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,13.677788
11,Plasma,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.047682,0.000364,0.007682,15.233282
12,T-cells,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.006278,0.008529,22.814613
13,Tumor,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.001874,0.0,0.000398,0.003255,0.021099,19.950264

In [32]:
s_pancreas.columns

Index(['cell_type', 's-PLG-F2R', 's-PLG-F2RL3', 's-PLG-PARD3', 's-PLG-F2RL1',
       's-PLG-F2RL2', 's-UCN2-CRHR1', 's-UCN2-CRHR2', 's-IL9-IL9R_IL2RG',
       's-FSHB-FSHR',
       ...
       's-INSL3-RXFP1', 's-INSL3-RXFP3', 's-INSL3-RXFP2', 's-INSL3-RXFP4',
       's-APLN-APLNR', 's-IAPP-CALCR', 's-IAPP-CALCRL',
       's-INHBA-ACVR1B_ACVR2B', 's-INHBA-ACVR1B_ACVR2A', 's-total-total'],
      dtype='object', length=1196)

In [39]:
n = len(s_pancreas)

In [40]:
matrix_pancreas = np.zeros((n-1,n-1))

for name_sender in s_pancreas.columns[1:] :
    l_sender = s_pancreas[name_sender]
    l_receiver = r_pancreas['r-' + name_sender[2:]]

    for i in range(n-1):
        for j in range(n-1):
            matrix_pancreas[i][j] += min(l_sender[i], l_receiver[j])

In [41]:
matrix_pancreas

array([[2.08442726e+01, 5.18912409e-01, 6.88637883e-01, 2.02409428e+01,
        2.08804186e+01, 2.25093784e+01, 1.94625023e+01, 1.08433641e+01,
        2.25890889e+01, 6.88637883e-01, 1.80244710e+01, 2.02416785e+01,
        2.17632276e+01],
       [5.98022772e+00, 3.39450946e-01, 5.09176420e-01, 5.49082186e+00,
        5.49172246e+00, 6.03500765e+00, 5.13126914e+00, 4.73518085e+00,
        5.93244706e+00, 5.09176420e-01, 6.00414552e+00, 5.77182882e+00,
        5.51720389e+00],
       [2.80760009e-02, 2.80214119e-02, 2.80214119e-02, 5.60428238e-02,
        2.90082645e-02, 5.60428238e-02, 5.51105602e-02, 5.52921138e-02,
        5.60428238e-02, 2.80214119e-02, 2.80760009e-02, 5.60428238e-02,
        5.60428238e-02],
       [1.91159876e+01, 5.98893367e-01, 8.45426020e-01, 3.70584488e+01,
        3.09489541e+01, 3.33824500e+01, 2.53196883e+01, 1.17550469e+01,
        3.56269131e+01, 8.45426020e-01, 1.81637610e+01, 2.52006424e+01,
        3.57073283e+01],
       [2.01858331e+01, 5.55168491e-01, 7.24893964e-01, 2.96215128e+01,
        3.22409895e+01, 3.13947897e+01, 2.50271546e+01, 1.14704768e+01,
        3.19229580e+01, 7.24893964e-01, 1.82537349e+01, 2.42733673e+01,
        3.13582770e+01],
       [2.15092122e+01, 5.64986522e-01, 8.45007283e-01, 3.27327564e+01,
        3.20434403e+01, 4.14982331e+01, 2.69558694e+01, 1.21140623e+01,
        4.00473426e+01, 8.45007283e-01, 1.94913966e+01, 2.75724815e+01,
        3.77833277e+01],
       [1.89598100e+01, 5.60041523e-01, 7.67530822e-01, 2.70589917e+01,
        2.53481706e+01, 2.76619550e+01, 2.88853022e+01, 1.08368932e+01,
        2.81625169e+01, 7.67530822e-01, 1.65632420e+01, 2.32078808e+01,
        2.74764725e+01],
       [1.37428263e+01, 5.60041523e-01, 7.45629736e-01, 1.48291382e+01,
        1.41938259e+01, 1.54531964e+01, 1.33337181e+01, 1.13135164e+01,
        1.57145045e+01, 7.45629736e-01, 1.39155549e+01, 1.44227125e+01,
        1.51199376e+01],
       [2.16605821e+01, 5.68892511e-01, 8.48913272e-01, 3.39375303e+01,
        3.25039067e+01, 3.99713967e+01, 2.73102335e+01, 1.22583718e+01,
        4.69183566e+01, 8.48913272e-01, 1.95354073e+01, 2.77513506e+01,
        4.25388808e+01],
       [2.80760009e-02, 2.80214119e-02, 2.80214119e-02, 5.60428238e-02,
        2.90082645e-02, 5.60428238e-02, 5.51105602e-02, 5.52921138e-02,
        5.60428238e-02, 2.80214119e-02, 2.80760009e-02, 5.60428238e-02,
        5.60428238e-02],
       [1.96448692e+01, 5.60041523e-01, 8.40062284e-01, 2.08811013e+01,
        2.12285121e+01, 2.30639257e+01, 1.96688632e+01, 1.11863608e+01,
        2.34087025e+01, 8.40062284e-01, 1.99080105e+01, 2.08164938e+01,
        2.25439734e+01],
       [1.95254776e+01, 5.60041523e-01, 8.40062284e-01, 2.58062758e+01,
        2.43156665e+01, 2.87156008e+01, 2.39314929e+01, 1.14524781e+01,
        2.88784552e+01, 8.40062284e-01, 1.77495881e+01, 2.71349199e+01,
        2.84999458e+01],
       [2.06324464e+01, 5.67151926e-01, 8.47172687e-01, 3.35976804e+01,
        3.22729949e+01, 3.76783913e+01, 2.65707196e+01, 1.21170070e+01,
        4.14817843e+01, 8.47172687e-01, 1.90381762e+01, 2.74125233e+01,
        4.32166124e+01]])